### ISSUE TITLE
- `GTExtensionSDK` required by `Podfile`

### ISSUE THREAD

**Issue by kakukeme** [GetuiLaboratory/GTExtensionSDK-iOS-CocoaPods#1]
[!] Unable to satisfy the following requirements:

- `GTExtensionSDK` required by `Podfile`

Specs satisfying the `GTExtensionSDK` dependency were found, but they required a higher minimum deployment target.

**Comment by kakukeme** [comment]
platform :ios, '8.0'
inhibit_all_warnings!

**Comment by GetuiLab** [comment]
您好，您这边是使用个推有什么问题吗，能否加官网首页技术支持的qq来沟通，这样会比较方便一些！！



support@getui.com
 
From: kakukeme
Date: 2017-12-07 14:33
To: GetuiLaboratory/GTExtensionSDK-iOS-CocoaPods
CC: Subscribed
Subject: [GetuiLaboratory/GTExtensionSDK-iOS-CocoaPods] - `GTExtensionSDK` required by `Podfile` (#1)
[!] Unable to satisfy the following requirements:
GTExtensionSDK required by Podfile
Specs satisfying the GTExtensionSDK dependency were found, but they required a higher minimum deployment target.

**Comment by GetuiLab** [comment]
您好，您这边是使用个推sdk有什么疑问吗，如果是的话，麻烦加下官网首页技术支持的qq，我们在讨论组沟通相关的问题！



support@getui.com
 
From: kakukeme
Date: 2017-12-07 14:33
To: GetuiLaboratory/GTExtensionSDK-iOS-CocoaPods
CC: Subscribed
Subject: Re: [GetuiLaboratory/GTExtensionSDK-iOS-CocoaPods] - `GTExtensionSDK` required by `Podfile` (#1)
platform :ios, '8.0'
inhibit_all_warnings!
